apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: hacbs-probe-payload
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: hacbs-probe-payload
    app.kubernetes.io/part-of: hacbs-probe-payload
  name: hacbs-probe-payload
  namespace: hacbs-probe-payload
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/instance: hacbs-probe-payload
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app.kubernetes.io/instance: hacbs-probe-payload
    spec:
      containers:
      - image: quay.io/jduimovich0/hacbs-probe-payload
        imagePullPolicy: Always
        livenessProbe:
          httpGet:
            path: /
            port: 8081
          initialDelaySeconds: 10
          periodSeconds: 10
        name: container-image
        ports:
        - containerPort: 8081
        readinessProbe:
          initialDelaySeconds: 10
          periodSeconds: 10
          tcpSocket:
            port: 8081
        resources: {}
status: {}
