apiVersion: route.openshift.io/v1
kind: Route
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: hacbs-probe-payload
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: hacbs-probe-payload
    app.kubernetes.io/part-of: hacbs-probe-payload
  name: hacbs-probe-payload
  namespace: hacbs-probe-payload
spec:
  port:
    targetPort: 8081
  tls:
    insecureEdgeTerminationPolicy: Redirect
    termination: edge
  to:
    kind: Service
    name: hacbs-probe-payload
    weight: 100
status: {}
